"""Cyclic continuation of the 24-h energy profile.

The real test day has 24 h of signals.  A schedule that starts at 06:00 and lasts longer than
18 h runs into the cyclic continuation (the day repeats, see DayProfile.minute_arrays).  This
script quantifies the issue and checks that the reported conclusions do not depend on it.

  A. how many feasible schedules of every method exceed the observed horizon (objective vectors);
  B. truncation: the front-quality comparison restricted to schedules that end inside the horizon
     (a method without such schedules on an instance scores 0, instances without any are skipped);
  C. policies only (their actions are re-generated by the stored checkpoints, exact and greedy):
     share of demand energy, cost and emissions that falls after the boundary, and a second
     continuation that holds the last available signal values (price, carbon, zero solar), with
     the responsiveness of the cost and emission weights recomputed under it.

Usage: python scripts/horizon_audit.py [--workers 6] [--skip-replay]
Output: results/summary/horizon_audit.json, macros merged into outputs/generated/numbers_rep.tex"""
import argparse
import glob
import json
import os
import pickle
import sys
from concurrent.futures import ProcessPoolExecutor

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from morl_fjsp.analysis import FEAS_TOL, indicators, load_baselines, reference, responsiveness  # noqa: E402
from morl_fjsp.latex import merge_macros  # noqa: E402
from morl_fjsp.metrics import eval_preferences  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = 360
BOUND = 1440 - START                       # minutes after the shift start at which the profile wraps
H_H = BOUND / 60.0                         # the same in hours (makespan units)
GROUPS = json.load(open(os.path.join(ROOT, "configs", "method_groups.json")))["main"]
INSTS = ["Mk%02d" % i for i in range(1, 11)] + ["La16", "La21"]


def replay_run(run):
    """Re-generate the 84 greedy schedules of one stored policy and split their energy at the boundary."""
    import torch
    from morl_fjsp.env import StaticGraph
    from morl_fjsp.model import PolicyNet
    from morl_fjsp.scenarios import benchmark_scenarios
    from morl_fjsp.sim import evaluate_actions
    from morl_fjsp.train import TrainConfig, rollout
    torch.set_num_threads(1)
    scs = benchmark_scenarios(os.path.join(ROOT, "data"), start_min=START, pv_factor=0.5, beta=0.9)
    W = eval_preferences()
    rdir = os.path.join(ROOT, "results", "runs", run)
    cfgd = json.load(open(os.path.join(rdir, "config.json")))
    cfg = TrainConfig(**{k: (tuple(v) if isinstance(v, list) else v) for k, v in cfgd.items()})
    net = PolicyNet(d=cfg.d_model, gat=cfg.gat, film=cfg.film, crit=getattr(cfg, "crit", True))
    net.load_state_dict(torch.load(os.path.join(rdir, "model.pt")))
    net.eval()
    stored = pickle.load(open(os.path.join(ROOT, "results", "policy_eval", "main", run + ".pkl"), "rb"))["results"]
    rng = np.random.default_rng(0)
    out = {}
    for s in scs:
        P = s.P
        _, acts, finals = rollout(net, [s] * len(W), W, rng, greedy=True, store=False,
                                  statics=[StaticGraph(P)] * len(W), mask_capacity=cfg.mask_capacity,
                                  allow_delay=cfg.delay)
        F0 = stored[s.name]["F"]
        rec = dict(viol=stored[s.name]["viol"], F=F0, max_dF=0.0, share_e=[], share_c=[], share_g=[],
                   cost_cyc=[], co2_cyc=[], cost_hold=[], co2_hold=[], cmax=[], F_replay=[], viol_replay=[])
        b = min(BOUND, P.H)
        price_h, pv_h, co2_h = P.price.copy(), P.pv.copy(), P.co2.copy()
        price_h[b:], pv_h[b:], co2_h[b:] = P.price[b - 1], P.pv[b - 1], P.co2[b - 1]
        for i, a in enumerate(acts):
            st = evaluate_actions(P, a)
            F = st.objectives()
            rec["F_replay"].append(F)
            rec["viol_replay"].append(st.violation())
            rec["max_dF"] = max(rec["max_dF"], float(np.max(np.abs(F - F0[i]) / np.maximum(np.abs(F0[i]), 1e-12))))
            D = st.D
            g = np.maximum(D - P.pv, 0.0)
            gh = np.maximum(D - pv_h, 0.0)
            cost = float((P.price * g).sum() / 60000.0)
            co2 = float((P.co2 * g).sum() / 60000.0)
            rec["cost_cyc"].append(cost); rec["co2_cyc"].append(co2)
            rec["cost_hold"].append(float((price_h * gh).sum() / 60000.0))
            rec["co2_hold"].append(float((co2_h * gh).sum() / 60000.0))
            rec["share_e"].append(float(D[b:].sum() / max(D.sum(), 1e-12)))
            rec["share_g"].append(float(g[b:].sum() / max(g.sum(), 1e-12)))
            rec["share_c"].append(float((P.price * g)[b:].sum() / max((P.price * g).sum(), 1e-12)))
            rec["cmax"].append(float(st.sc[0] / 60.0))
        out[s.name] = {k: (np.array(v) if isinstance(v, list) else v) for k, v in rec.items()}
    return run, out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--skip-replay", action="store_true")
    ap.add_argument("--reuse", action="store_true", help="read results/summary/horizon_replay.pkl instead of regenerating the schedules")
    args = ap.parse_args()
    base = load_baselines(ROOT)
    pol = {}
    for lab, names in GROUPS.items():
        for n in names:
            pol[n] = (lab, pickle.load(open(os.path.join(ROOT, "results", "policy_eval", "main", n + ".pkl"), "rb"))["results"])
    M, out = {}, {}

    # ---------------------------------------------------------------- A. crossing frequency
    def feas_sets(inst):
        rd = {}
        for lab, names in GROUPS.items():
            rd[lab] = [pol[n][1][inst]["F"][pol[n][1][inst]["viol"] <= FEAS_TOL] for n in names]
        b = base[inst]
        rd["PWG"] = [b["pwg"]["F"][b["pwg"]["viol"] <= FEAS_TOL]]
        for algo, lab in (("nsga2", "NSGA-II"), ("nsga3", "NSGA-III")):
            rd[lab] = [r["F"][r["G"] <= FEAS_TOL] for r in b["moea"][algo]]
        return rd

    tag = {"DP-PreCo-GRL": "Preco", "LS-GRL": "Ls", "PWG": "Pwg", "NSGA-II": "Nsgaii", "NSGA-III": "Nsgaiii"}
    cross = {l: [0, 0] for l in tag}
    per_inst = {l: {} for l in tag}
    for inst in INSTS:
        for lab, sets in feas_sets(inst).items():
            c = sum(int((F[:, 0] > H_H).sum()) for F in sets)
            n = sum(len(F) for F in sets)
            cross[lab][0] += c; cross[lab][1] += n
            per_inst[lab][inst] = c / max(n, 1)
    out["crossing_share"] = {l: c / n for l, (c, n) in cross.items()}
    out["crossing_share_per_instance"] = per_inst
    for l, t in tag.items():
        M[f"horizonCross{t}"] = f"{100 * cross[l][0] / cross[l][1]:.0f}"
    M["horizonHours"] = f"{H_H:.0f}"
    M["horizonInstNsgaCross"] = str(sum(per_inst["NSGA-II"][i] > 0.5 for i in INSTS))

    # ---------------------------------------------------------------- B. truncation to the observed horizon
    hv_full, hv_trunc, used = {l: [] for l in tag}, {l: [] for l in tag}, []
    for inst in INSTS:
        full = feas_sets(inst)
        trunc = {l: [F[F[:, 0] <= H_H] for F in sets] for l, sets in full.items()}
        if not any(len(F) for sets in trunc.values() for F in sets):
            continue
        used.append(inst)
        for rd, store in ((full, hv_full), (trunc, hv_trunc)):
            R, ideal, nadir = reference(rd)
            ind, _ = indicators(rd, R, ideal, nadir)
            for l in tag:
                store[l].append(float(np.mean(ind[l]["hv"])))
    out["truncation"] = dict(instances=used, full={l: float(np.mean(v)) for l, v in hv_full.items()},
                             truncated={l: float(np.mean(v)) for l, v in hv_trunc.items()},
                             per_instance_truncated={l: v for l, v in hv_trunc.items()})
    M["horizonTruncN"] = str(len(used))
    for l, t in tag.items():
        M[f"horizonFullHv{t}"] = f"{np.mean(hv_full[l]):.3f}"
        M[f"horizonTruncHv{t}"] = f"{np.mean(hv_trunc[l]):.3f}"
    out["truncation"]["rank_preserved"] = bool(
        np.argsort([np.mean(hv_full[l]) for l in tag]).tolist() == np.argsort([np.mean(hv_trunc[l]) for l in tag]).tolist())

    # ---------------------------------------------------------------- C. policies: replay
    if not args.skip_replay:
        runs = [n for names in GROUPS.values() for n in names]
        rp = os.path.join(ROOT, "results", "summary", "horizon_replay.pkl")
        if args.reuse and os.path.exists(rp):
            res = pickle.load(open(rp, "rb"))
        else:
            with ProcessPoolExecutor(args.workers) as ex:
                res = dict(ex.map(replay_run, runs))
        W = eval_preferences()
        pickle.dump({n: {i: {k: v for k, v in r.items()} for i, r in res[n].items()} for n in res},
                    open(os.path.join(ROOT, "results", "summary", "horizon_replay.pkl"), "wb"))
        summ = {}
        for lab, names in GROUPS.items():
            share_e, share_c, cost_rel, co2_rel, rho_c, rho_e, rho_c0, rho_e0, ncross = [], [], [], [], [], [], [], [], 0
            nfeas = nmis = ntot = 0
            worst = 0.0
            mis_runs = {}
            for n in names:
                for inst in INSTS:
                    r = res[n][inst]
                    Fr = np.array(r["F_replay"])
                    rel = np.max(np.abs(Fr - r["F"]) / np.maximum(np.abs(r["F"]), 1e-12), axis=1)
                    nmis += int((rel > 1e-9).sum()); ntot += len(rel)
                    mis_runs[n] = mis_runs.get(n, 0) + int((rel > 1e-9).sum())
                    worst = max(worst, r["max_dF"])
                    ok = np.array(r["viol_replay"]) <= FEAS_TOL          # feasibility of the regenerated schedule
                    cross_i = ok & (r["cmax"] > H_H)
                    nfeas += int(ok.sum()); ncross += int(cross_i.sum())
                    share_e += r["share_e"][ok].tolist(); share_c += r["share_c"][ok].tolist()
                    cost_rel += ((r["cost_hold"] / r["cost_cyc"] - 1.0)[cross_i]).tolist()
                    co2_rel += ((r["co2_hold"] / r["co2_cyc"] - 1.0)[cross_i]).tolist()
                    Fh = Fr.copy(); Fh[:, 1], Fh[:, 2] = r["cost_hold"], r["co2_hold"]
                    viol_r = np.array(r["viol_replay"])
                    rho_h = responsiveness(Fh, W, viol_r); rho_0 = responsiveness(Fr, W, viol_r)
                    rho_c.append(rho_h[1]); rho_e.append(rho_h[2]); rho_c0.append(rho_0[1]); rho_e0.append(rho_0[2])
            t = tag[lab]
            summ[lab] = dict(n_feasible=nfeas, n_crossing=ncross, max_relative_dF=worst,
                             n_schedules=ntot, n_mismatch_vs_stored=nmis, mismatch_per_run=mis_runs,
                             mean_energy_share_after=float(np.mean(share_e)),
                             mean_cost_share_after=float(np.mean(share_c)),
                             crossing_cost_change_hold_median=float(np.median(cost_rel)),
                             crossing_cost_change_hold_iqr=[float(x) for x in np.percentile(cost_rel, [25, 75])],
                             crossing_co2_change_hold_median=float(np.median(co2_rel)),
                             rho_cost_cyclic=float(np.nanmean(rho_c0)), rho_co2_cyclic=float(np.nanmean(rho_e0)),
                             rho_cost_hold=float(np.nanmean(rho_c)), rho_co2_hold=float(np.nanmean(rho_e)))
            M[f"horizonMismatch{t}"] = str(nmis)
            M[f"horizonEnAfter{t}"] = f"{100 * np.mean(share_e):.0f}"
            M[f"horizonCostAfter{t}"] = f"{100 * np.mean(share_c):.0f}"
            M[f"horizonHoldCost{t}"] = f"{100 * np.median(cost_rel):+.0f}"
            M[f"horizonRhoCostHold{t}"] = f"{np.nanmean(rho_c):+.2f}"
            M[f"horizonRhoCoHold{t}"] = f"{np.nanmean(rho_e):+.2f}"
            M[f"horizonRhoCostCyc{t}"] = f"{np.nanmean(rho_c0):+.2f}"
        out["policies"] = summ
        M["horizonReplayN"] = f"{sum(v['n_schedules'] for v in summ.values()):,}".replace(",", "{,}")
        M["horizonReplayMismatch"] = str(sum(v["n_mismatch_vs_stored"] for v in summ.values()))
        M["horizonReplayExact"] = f"{sum(v['n_schedules'] - v['n_mismatch_vs_stored'] for v in summ.values()):,}".replace(",", "{,}")
        M["horizonReplayMaxDiffPreco"] = f"{summ['DP-PreCo-GRL']['max_relative_dF']:.1e}".replace("e-", "\\times10^{-") + "}"
        M["horizonReplayMaxDiffLs"] = f"{100 * summ['LS-GRL']['max_relative_dF']:.0f}"
    json.dump(out, open(os.path.join(ROOT, "results", "summary", "horizon_audit.json"), "w"), indent=1)
    merge_macros(os.path.join(ROOT, "outputs", "generated", "numbers_rep.tex"), M)
    print(json.dumps(out, indent=1)[:6000])
    print(M)


if __name__ == "__main__":
    main()
